# Generated by Django 4.2 on 2024-04-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updeted',
            new_name='updated',
        ),
    ]
